In [1]:
pip install ipython-sql sqlalchemy

Requirement already satisfied: ipython-sql in c:\anaconda3\lib\site-packages (0.5.0)
Requirement already satisfied: sqlalchemy in c:\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: prettytable in c:\anaconda3\lib\site-packages (from ipython-sql) (3.9.0)
Requirement already satisfied: ipython in c:\anaconda3\lib\site-packages (from ipython-sql) (9.7.0)
Requirement already satisfied: sqlparse in c:\anaconda3\lib\site-packages (from ipython-sql) (0.5.5)
Requirement already satisfied: six in c:\anaconda3\lib\site-packages (from ipython-sql) (1.17.0)
Requirement already satisfied: ipython-genutils in c:\anaconda3\lib\site-packages (from ipython-sql) (0.2.0)
Requirement already satisfied: greenlet>=1 in c:\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: colorama>=0.4.4 in c:\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.4.6)
Requirement already satisfied: decorator>=4.3.2 in c:\anaconda3\lib\site-packages (from ipython->ipython-sql) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in c:\anaconda3\lib\site-packages (from ipython->ipython-sql) (1.1.1)
Requirement already satisfied: jedi>=0.18.1 in c:\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.19.2)
Requirement already satisfied: matplotlib-inline>=0.1.5 in c:\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.2.1)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\anaconda3\lib\site-packages (from ipython->ipython-sql) (3.0.52)
Requirement already satisfied: pygments>=2.11.0 in c:\anaconda3\lib\site-packages (from ipython->ipython-sql) (2.19.2)
Requirement already satisfied: stack_data>=0.6.0 in c:\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.6.3)
Requirement already satisfied: traitlets>=5.13.0 in c:\anaconda3\lib\site-packages (from ipython->ipython-sql) (5.14.3)
Requirement already satisfied: wcwidth in c:\anaconda3\lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython->ipython-sql) (0.2.13)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in c:\anaconda3\lib\site-packages (from jedi>=0.18.1->ipython->ipython-sql) (0.8.5)
Requirement already satisfied: executing>=1.2.0 in c:\anaconda3\lib\site-packages (from stack_data>=0.6.0->ipython->ipython-sql) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in c:\anaconda3\lib\site-packages (from stack_data>=0.6.0->ipython->ipython-sql) (3.0.0)
Requirement already satisfied: pure_eval in c:\anaconda3\lib\site-packages (from stack_data>=0.6.0->ipython->ipython-sql) (0.2.3)
Note: you may need to restart the kernel to use updated packages.

In [2]:
%load_ext sql

In [3]:
%sql sqlite:///mydatabase.db

In [1]:
%sql mssql+pyodbc://@localhost/Sample_Superstore?driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=yes

UsageError: Line magic function `%sql` not found.

In [2]:
%config SqlMagic.autopandas = True

In [16]:
%%sql
SELECT * FROM Sales.SalesOrderDetail

 * mssql+pyodbc://@localhost/AdventureWorks2019?driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=yes
   mssql+pyodbc://@localhost/store?driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=yes
   sqlite:///mydatabase.db
Done.

,SalesOrderID,SalesOrderDetailID,CarrierTrackingNumber,OrderQty,ProductID,SpecialOfferID,UnitPrice,UnitPriceDiscount,LineTotal,rowguid,ModifiedDate
0,43659,1,4911-403C-98,1,776,1,2024.9940,0.0000,2024.994000,B207C96D-D9E6-402B-8470-2CC176C42283,2011-05-31
1,43659,2,4911-403C-98,3,777,1,2024.9940,0.0000,6074.982000,7ABB600D-1E77-41BE-9FE5-B9142CFC08FA,2011-05-31
2,43659,3,4911-403C-98,1,778,1,2024.9940,0.0000,2024.994000,475CF8C6-49F6-486E-B0AD-AFC6A50CDD2F,2011-05-31
3,43659,4,4911-403C-98,1,771,1,2039.9940,0.0000,2039.994000,04C4DE91-5815-45D6-8670-F462719FBCE3,2011-05-31
4,43659,5,4911-403C-98,1,772,1,2039.9940,0.0000,2039.994000,5A74C7D2-E641-438E-A7AC-37BF23280301,2011-05-31
...,...,...,...,...,...,...,...,...,...,...,...
121312,75122,121313,None,1,878,1,21.9800,0.0000,21.980000,8CAD6675-18CC-4F47-8287-97B41A8EE47D,2014-06-30
121313,75122,121314,None,1,712,1,8.9900,0.0000,8.990000,84F1C363-1C50-4442-BE16-541C59B6E12C,2014-06-30
121314,75123,121315,None,1,878,1,21.9800,0.0000,21.980000,C18B6476-429F-4BB1-828E-2BE5F82A0A51,2014-06-30
121315,75123,121316,None,1,879,1,159.0000,0.0000,159.000000,75A89C6A-C60A-47EA-8A52-B52A9C435B64,2014-06-30
121316,75123,121317,None,1,712,1,8.9900,0.0000,8.990000,73646D26-0461-450D-8019-2C6C858619CA,2014-06-30

In [17]:
%%sql
SELECT * FROM Sales.SalesOrderDetail

 * mssql+pyodbc://@localhost/AdventureWorks2019?driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=yes
   mssql+pyodbc://@localhost/store?driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=yes
   sqlite:///mydatabase.db
Done.

,SalesOrderID,SalesOrderDetailID,CarrierTrackingNumber,OrderQty,ProductID,SpecialOfferID,UnitPrice,UnitPriceDiscount,LineTotal,rowguid,ModifiedDate
0,43659,1,4911-403C-98,1,776,1,2024.9940,0.0000,2024.994000,B207C96D-D9E6-402B-8470-2CC176C42283,2011-05-31
1,43659,2,4911-403C-98,3,777,1,2024.9940,0.0000,6074.982000,7ABB600D-1E77-41BE-9FE5-B9142CFC08FA,2011-05-31
2,43659,3,4911-403C-98,1,778,1,2024.9940,0.0000,2024.994000,475CF8C6-49F6-486E-B0AD-AFC6A50CDD2F,2011-05-31
3,43659,4,4911-403C-98,1,771,1,2039.9940,0.0000,2039.994000,04C4DE91-5815-45D6-8670-F462719FBCE3,2011-05-31
4,43659,5,4911-403C-98,1,772,1,2039.9940,0.0000,2039.994000,5A74C7D2-E641-438E-A7AC-37BF23280301,2011-05-31
...,...,...,...,...,...,...,...,...,...,...,...
121312,75122,121313,None,1,878,1,21.9800,0.0000,21.980000,8CAD6675-18CC-4F47-8287-97B41A8EE47D,2014-06-30
121313,75122,121314,None,1,712,1,8.9900,0.0000,8.990000,84F1C363-1C50-4442-BE16-541C59B6E12C,2014-06-30
121314,75123,121315,None,1,878,1,21.9800,0.0000,21.980000,C18B6476-429F-4BB1-828E-2BE5F82A0A51,2014-06-30
121315,75123,121316,None,1,879,1,159.0000,0.0000,159.000000,75A89C6A-C60A-47EA-8A52-B52A9C435B64,2014-06-30
121316,75123,121317,None,1,712,1,8.9900,0.0000,8.990000,73646D26-0461-450D-8019-2C6C858619CA,2014-06-30